#ifndef PLATFORMER_SPRITES_H
#define PLATFORMER_SPRITES_H

static const char idle0_png_b64[] =
    "iVBORw0KGgoAAAANSUhEUgAAAFAAAABgCAYAAABqWkvzAAA4f0lEQVR42u2de5BcV3XfP7e3z9z3M+9i"
    "...TRUNCATED_FOR_TOOL...";

#endif